<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lst_InforOrder</name>
   <tag></tag>
   <elementGuidId>ec6e8b2d-5647-48de-bf18-f323e66fb542</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tbody[contains(@class,'MuiTableBody-root')]//td[contains(text(),'#5419')]/following-sibling::td</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
